/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycard;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowListener;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.ByteArrayOutputStream;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.lang.invoke.MethodHandles;
import java.math.BigInteger;
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.RSAPublicKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageOutputStream;
import javax.naming.spi.DirStateFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author hoang
 */
public class BusForm extends javax.swing.JFrame {
    static info info;
    static DBConnection db;
    static theBus thebus;
    private Boolean input= false;
    static boolean cardready= false;
    static boolean connected= false;
     private boolean khoitao = false;
    static byte[] rsaPubKey = new byte[256];
    private int soid=0;
    private int saipin= 3;
     static BufferedImage c;
    /**
     * Creates new form SCForm
     */
    public BusForm() {
        info = new info();
        thebus = new theBus();
        initComponents();
        db=new DBConnection(info);
       db.connect();
    }

    //hien thi apdu lenh len GUI
    public void setCommandAPDU(byte[] cmnds, byte lc,byte[] data, byte le) {
      
        //data
        String temp = "";
        for (int i = 0; i < data.length; i++) {
            temp += thebus.byteToHex(data[i]);
            temp += " ";
        }
      
    }
    //hien thi apdu phan hoi len
    public void setResponseAPDU(byte[] datares,short le) {
        int status1 = thebus.resAPDU.getSW1();
        int status2 = thebus.resAPDU.getSW2();
     
        if (le != 0 && datares.length != 0) {
            //hien thi du lieu ra
            String temp = "";
            for (int i = 0; i < datares.length; i++) {
                temp += thebus.byteToHex(datares[i]);
                temp += " ";
            }
          
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel4 = new javax.swing.JPanel();
        initCard = new custom.MyButton();
        sendToApplet = new custom.MyButton();
        unlockCard = new custom.MyButton();
        deleteCard = new custom.MyButton();
        btnConnect = new custom.MyButton();
        btnDisconnect = new custom.MyButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnXemtt = new custom.MyButton();
        txt_pin = new custom.PasswordField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 520, -1));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Card operation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        initCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycard/icon/original.png"))); // NOI18N
        initCard.setText("INIT CARD");
        initCard.setRadius(50);
        initCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initCardActionPerformed(evt);
            }
        });

        sendToApplet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycard/icon/address-card.png"))); // NOI18N
        sendToApplet.setText("SEND");
        sendToApplet.setRadius(50);
        sendToApplet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToAppletActionPerformed(evt);
            }
        });

        unlockCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycard/icon/unlock.png"))); // NOI18N
        unlockCard.setText("UNLOCK CARD");
        unlockCard.setRadius(50);
        unlockCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockCardActionPerformed(evt);
            }
        });

        deleteCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycard/icon/delete.png"))); // NOI18N
        deleteCard.setText("DELETE CARD");
        deleteCard.setRadius(50);
        deleteCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCardActionPerformed(evt);
            }
        });

        btnConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycard/icon/connect.png"))); // NOI18N
        btnConnect.setText("CONNECT CARD");
        btnConnect.setRadius(50);
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnDisconnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycard/icon/disconnect.png"))); // NOI18N
        btnDisconnect.setText("DISCONNECT CARD");
        btnDisconnect.setRadius(50);
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteCard, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(initCard, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendToApplet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unlockCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDisconnect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(btnConnect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initCard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendToApplet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unlockCard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnDisconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel11.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Login Card", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Enter PIN:");

        btnXemtt.setText("Enter");
        btnXemtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemttActionPerformed(evt);
            }
        });

        txt_pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pinActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycard/icon/download.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnXemtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXemtt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );

        jPanel11.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 540, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int check_pin(String pin) {
        short lc = (short) pin.length(); //do dai du lieu gui vao applet
        short le = 1;//du lieu nhan mong doi (Le)
        byte[] cmd = {(byte) 0xA0, (byte) 0x19, (byte) 0x00, (byte) 0x00};
        byte[] data = pin.getBytes();
        setCommandAPDU(cmd, (byte)lc, data,(byte)le);
        thebus.sendAPDUtoApplet(cmd, data);
        byte[] dataRes = thebus.resAPDU.getData();
        int lenRes= thebus.resAPDU.getNr() ;
        setResponseAPDU(dataRes, (byte)lenRes);
        //String a = new String(dataRes);
        if (dataRes[0] == (byte)0x01) {//đúng mã PIN
            return 1;
        } else if(dataRes[0] == (byte)0x00){
            return 0;
        }else return 2;
    }
    private void sendToAppletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToAppletActionPerformed
        // TODO add your handling code here:
         if (connected == true) {
            if (khoitao == true && input == false) {
                setImage(info.getAvatar());
                //chuyen du lieu xuong applet
                String sothe = info.getSothe();
                String hoten = info.getHoten();
                String ngaysinh = info.getNgaysinh();
                String loaithe = info.getLoaithe();
                String thoihan = info.getThoihan();
                String pin = info.getPin();
                String arraysend = sothe.concat(".").concat(hoten).concat(".").concat(ngaysinh).concat(".").concat(loaithe).concat(".").concat(thoihan).concat(".").concat(pin);
                System.out.println("send:" + arraysend);
                int lc = arraysend.length();
                byte datalen = (byte) lc; //do dai du lieu gui vao applet
                byte[] cmd = {(byte) 0xA0, (byte) 0x10, (byte) 0x00, (byte) 0x00};
                byte[] data = arraysend.getBytes();
                setCommandAPDU(cmd, (byte) lc, data, (byte) 0);
                thebus.sendAPDUtoApplet(cmd, data);
                rsaPubKey = thebus.resAPDU.getData();
                info.setRsaPubKey(rsaPubKey);
                
                int le = thebus.resAPDU.getNr();
                setResponseAPDU(rsaPubKey, (byte) le);//hien thi du lieu phan hoi tu applet
                if (thebus.resAPDU.getSW1() == 0x90) {
                    JOptionPane.showMessageDialog(this, "Lưu thông tin thành công");
                    db.insert(info);
                    input = true;
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi! Hãy khởi tạo lại thông tin");
                    khoitao = false;
                    input = false;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Chưa khởi tạo thông tin");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa connect thẻ");        // TODO add your handling code here:
        }
    }//GEN-LAST:event_sendToAppletActionPerformed

    private void initCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initCardActionPerformed
        // TODO add your handling code here:
         if(connected == true){
            if (khoitao == false) {
                soid++;
                Formnhap initform = new Formnhap(soid);
                initform.setVisible(true);
                initform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                khoitao = true;
               
            }
            else JOptionPane.showMessageDialog(this, "Thẻ đã khởi tạo dữ liệu");
        }else JOptionPane.showMessageDialog(this, "Chưa connect thẻ");
    }//GEN-LAST:event_initCardActionPerformed

    private void deleteCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCardActionPerformed
  if(connected ==true){
            if(khoitao == false || input == false){ JOptionPane.showMessageDialog(null, "Thẻ chưa có dữ liệu.");
            }else{
                byte[] cmd = {(byte) 0xA0, (byte) 0x18, (byte) 0x00, (byte) 0x00};
                byte[] data = {0};
                setCommandAPDU(cmd,(byte)0, data, (byte)0);//hien thi apdu cmd len GUI
                thebus.sendAPDUtoApplet(cmd);
                byte[] dataRes= thebus.resAPDU.getData();
                int le= thebus.resAPDU.getNr();
                setResponseAPDU(dataRes,(short) le);//hien thi du lieu phan hoi tu applet
                JOptionPane.showMessageDialog(this, "Thẻ đã xóa dữ liệu.");
                input=false;
                khoitao=false;
                cardready=false;
            }   
        }else JOptionPane.showMessageDialog(this, "Chưa connect thẻ");        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCardActionPerformed

    private void unlockCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlockCardActionPerformed
          if(connected==true){
            if(khoitao == true && input == true){
                byte[] cmd = {(byte) 0xA0, (byte) 0x20, (byte) 0x00, (byte) 0x00};
                byte[] data= {0};
                thebus.sendAPDUtoApplet(cmd);
                byte[] dataRes= thebus.resAPDU.getData();
                int le= thebus.resAPDU.getNr();
                setResponseAPDU(dataRes,(short) le);//hien thi du lieu phan hoi tu applet
                saipin=3;
                JOptionPane.showMessageDialog(this, "Thẻ đã được mở khóa.");
            }else{
                JOptionPane.showMessageDialog(this, "Thẻ chưa khởi tạo");
            }
        }else JOptionPane.showMessageDialog(this, "Chưa connect thẻ");        // TODO add your handling code here:
    }//GEN-LAST:event_unlockCardActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
          if (thebus.connectApplet() == true) {;//thiet lap ket noi
            byte[] cmd = {(byte) 0x00, (byte) 0xA4, (byte) 0x04, (byte) 0x00};// select
            //mang data gui di la RID,PIX
            byte[] data = {(byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00};
//            byte[] data = {(byte) 0x00, (byte) 0x11, (byte) 0x22, (byte) 0x33, (byte) 0x44, (byte) 0x55};
            byte lc = 6;
            byte le_expect = 2;
            setCommandAPDU(cmd, lc, data, le_expect);//hien thi apdu cmd
            thebus.sendAPDUtoApplet(cmd, data);
            byte[] dataRes = thebus.resAPDU.getData();
            int le = thebus.resAPDU.getNr();
            setResponseAPDU(dataRes, (short) le);//hien thi du lieu phan hoi tu applet
            btnConnect.setText("Connecting...");
            btnConnect.setColor(Color.green);
            btnDisconnect.setText("Disconnect");
            btnDisconnect.setColor(Color.gray);
            connected = true;
        } else
            JOptionPane.showMessageDialog(this, "Kết nối không thành công. Hãy thử lại.");
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        // TODO add your handling code here:
         if (thebus.disconnectApplet() == true) {

      //      txt_pin.setText("");

            btnConnect.setText("Connect");
            btnConnect.setColor(Color.green);
            btnDisconnect.setText("disconnected");
            btnDisconnect.setColor(Color.red);
            connected = false;
            cardready = false;
        } else
            JOptionPane.showMessageDialog(this, "Ngắt kết nối không thành công.");
    }//GEN-LAST:event_btnDisconnectActionPerformed

    private void btnXemttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemttActionPerformed
 if(connected == true && input== true && khoitao == true){
           String pin = Arrays.toString(txt_pin.getPassword()); // Chuỗi ban đầu: "[1,2,3]"
            pin = pin.replaceAll("\\D", ""); // Chỉ giữ lại các chữ số

            if(pin.length() != 6){
                JOptionPane.showMessageDialog(this, "Mã PIN gồm 6 kí tự");
            }
            if(check_pin(pin) == 0){
                JOptionPane.showMessageDialog(this ,"Mã PIN sai. Vui lòng nhập lại.\n(Số lần nhập sai còn lại:"+--saipin+")");
                
               txt_pin.setText("");
                cardready = false;
            }
            else if (check_pin(pin) == 1){
               try {
                   cardready =true;
                   saipin =3;
                   getImage(info.getAvatar());
                   byte[] cmd = {(byte) 0xA0, (byte) 0x11, (byte) 0x00, (byte) 0x00};
                   byte[] data= {0};
                   setCommandAPDU(cmd,(byte)0, data, (byte)0);//hien thi apdu cmd len GUI
                   thebus.sendAPDUtoApplet(cmd);
                   byte[] dataRes = thebus.resAPDU.getData();
                   int le = thebus.resAPDU.getNr();
                   setResponseAPDU(dataRes, (byte)le);//hien thi du lieu phan hoi tu applet
                   String tach = new String(dataRes) ;
                   //System.out.print("a:"+tach);
                   String[] a = tach.split(":");
                   String st = a[0];
                   String ht = a[1];
                   String ns = a[2];
                   String lt = a[3];
                   String th = a[4];
                   byte[] cmd1 = {(byte) 0xA0, (byte) 0x21, (byte) 0x00, (byte) 0x00};
                   thebus.sendAPDUtoApplet(cmd1);
                   byte[] b = thebus.resAPDU.getData();
                   String sodu = "";
                   for (int i = 0; i < b.length; i++) {
                       sodu += thebus.byteToHex(b[i]);
                   }
                   int sd = Integer.valueOf(sodu,16).intValue()*1000;
                   a[5] =String.valueOf(sd);
                   
                   userForm user = new userForm(a,c);
                   user.setVisible(true);
                   user.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               } catch (IOException ex) {
                   Logger.getLogger(BusForm.class.getName()).log(Level.SEVERE, null, ex);
               }
            }else JOptionPane.showMessageDialog(this, "Bạn đã nhập sai quá số lần cho phép. Thẻ đã bị khóa!");
        }else JOptionPane.showMessageDialog(this, "Thẻ chưa sẵn sàng");         // TODO add your handling code here:
    }//GEN-LAST:event_btnXemttActionPerformed

    private void txt_pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusForm().setVisible(true);
            }
            
        });
    }
    public static void setImage(byte [] img){
        if(img == null) return;
        byte[] cmd = {(byte) 0xA0, (byte) 0x12, (byte) 0x01, (byte) 0x00};
        thebus.sendAPDUtoApplet(cmd);
        int sendlen = img.length;
        System.out.println("ảnh gửi:" +img);
        byte[] cmnd = {(byte) 0xA0, (byte) 0x12, (byte) 0x02, (byte) 0x00};
        int pointer = 0;
        byte[] temp = new byte[255];
        int datalen = 255;
        while(sendlen >0){
            System.arraycopy(img, pointer, temp, 0, datalen);
            thebus.sendAPDUtoApplet(cmnd, temp);
            pointer += 255;
            sendlen -=255;
            if(sendlen <255){
                datalen = sendlen;
            }
        }
//        byte[] cmd_encrypt = {(byte) 0xA0, (byte) 0x12, (byte) 0x03, (byte) 0x00};
//        thebus.sendAPDUtoApplet(cmd_encrypt);
    }
    public static void getImage(byte [] img) throws IOException{
         if(img == null) return;
         //        byte[] cmd_decrypt = {(byte) 0xA0, (byte) 0x13, (byte) 0x03, (byte) 0x00};
//        thebus.sendAPDUtoApplet(cmd_decrypt);
byte[] cmd = {(byte) 0xA0, (byte) 0x13, (byte) 0x01, (byte) 0x00};
thebus.sendAPDUtoApplet(cmd);
int sendlen = img.length;
byte[] cmnd = {(byte) 0xA0, (byte) 0x13, (byte) 0x02, (byte) 0x00};
byte[] resimg= new byte[sendlen];
int pointer=0;
int datalen = 255;
while(sendlen >0){
    thebus.sendAPDUtoApplet(cmnd);
    byte[] temp = thebus.resAPDU.getData();
    System.arraycopy(temp, 0, resimg, pointer, datalen);
    pointer += 255;
    sendlen -= 255;
    if(sendlen<255){
        datalen = sendlen;
    }
       
}
 ByteArrayInputStream bais= new ByteArrayInputStream(resimg);
        c = ImageIO.read(bais);
System.out.println("ảnh res:" +resimg);
       
    }
    
   static String randomString(int n)
    {
        // chose a Character random from this String
        String AlphaNumericString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvxyz";
                               
        // create StringBuffer size of AlphaNumericString
        StringBuilder sb = new StringBuilder(n);
  
        for (int i = 0; i < n; i++) {
            // generate a random number between
            // 0 to AlphaNumericString variable length
            int index = (int)(AlphaNumericString.length() * Math.random());
            // add Character one by one in end of sb
            sb.append(AlphaNumericString.charAt(index));
        }
        return sb.toString();
    }
    private void setnull(){
      
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.MyButton btnConnect;
    private custom.MyButton btnDisconnect;
    private custom.MyButton btnXemtt;
    private custom.MyButton deleteCard;
    private javax.swing.Box.Filler filler1;
    private custom.MyButton initCard;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private custom.MyButton sendToApplet;
    private custom.PasswordField txt_pin;
    private custom.MyButton unlockCard;
    // End of variables declaration//GEN-END:variables
}
