/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mycard;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class userForm extends javax.swing.JFrame {

    /**
     * Creates new form userForm
     */
    public userForm(String[] a,  BufferedImage c) throws IOException {

        initComponents();
        txt_sothe.setText(a[0]);
        txt_hoten.setText(a[1]);
        txt_ngaysinh.setText(a[2]);
        txt_loaithe.setText(a[3]);
        txt_thoihan.setText(a[4]);
        txt_sodu.setText(a[5]); 
        ImageIcon icon= new ImageIcon(c.getScaledInstance(anhthe.getWidth(),anhthe.getHeight(), Image.SCALE_SMOOTH));
        icon.getImage();
        anhthe.setIcon(icon);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_info = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        anhthe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_sothe = new custom.TextField();
        txt_hoten = new custom.TextField();
        txt_ngaysinh = new custom.TextField();
        txt_loaithe = new custom.TextField();
        txt_thoihan = new custom.TextField();
        txt_sodu = new custom.TextField();
        jPanel5 = new javax.swing.JPanel();
        btn_changePIN = new custom.MyButton();
        btn_capnhat = new custom.MyButton();
        Btn_thayanh = new custom.MyButton();
        btn_thanhtoan = new custom.MyButton();
        bnt_naptien = new custom.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_info.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_info.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Infomation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel_info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Card type:");
        jPanel_info.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 90, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("THẺ XE BUÝT");
        jPanel_info.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 144, 36));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Card Number:");
        jPanel_info.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, 25));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Full Name:");
        jPanel_info.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 80, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Date of birth:");
        jPanel_info.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, 20));

        anhthe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jPanel_info.add(anhthe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 170));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Expired:");
        jPanel_info.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Balance:");
        jPanel_info.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 70, -1));
        jPanel_info.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("VND");
        jPanel_info.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        txt_sothe.setEditable(false);
        jPanel_info.add(txt_sothe, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 170, -1));

        txt_hoten.setEditable(false);
        jPanel_info.add(txt_hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 170, -1));

        txt_ngaysinh.setEditable(false);
        jPanel_info.add(txt_ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 170, -1));

        txt_loaithe.setEditable(false);
        jPanel_info.add(txt_loaithe, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 170, -1));

        txt_thoihan.setEditable(false);
        jPanel_info.add(txt_thoihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 170, -1));

        txt_sodu.setEditable(false);
        jPanel_info.add(txt_sodu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 110, -1));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Main functions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_changePIN.setText("Change PIN");
        btn_changePIN.setRadius(50);
        btn_changePIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changePINActionPerformed(evt);
            }
        });
        jPanel5.add(btn_changePIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, 50));

        btn_capnhat.setText("Edit Information");
        btn_capnhat.setRadius(50);
        btn_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatActionPerformed(evt);
            }
        });
        jPanel5.add(btn_capnhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 130, 50));

        Btn_thayanh.setText("Change Image");
        Btn_thayanh.setRadius(50);
        Btn_thayanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_thayanhActionPerformed(evt);
            }
        });
        jPanel5.add(Btn_thayanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 153, 120, 50));

        btn_thanhtoan.setText("Check out");
        btn_thanhtoan.setRadius(50);
        jPanel5.add(btn_thanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 153, 130, 50));

        bnt_naptien.setText("Recharge");
        bnt_naptien.setRadius(50);
        jPanel5.add(bnt_naptien, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_info, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_info, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_changePINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changePINActionPerformed

        updatePIN updatepin = new updatePIN();
        updatepin.setVisible(true);
        updatepin.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_btn_changePINActionPerformed

    private void btn_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatActionPerformed
        updateInfor updateinfo = new updateInfor(txt_sothe.getText(), txt_hoten.getText(), txt_ngaysinh.getText(), txt_loaithe.getText(), txt_thoihan.getText());
        updateinfo.setVisible(true);
        updateinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btn_capnhatActionPerformed

    private void Btn_thayanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_thayanhActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnValue = fc.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            BufferedImage bimage;
            try{
                bimage = ImageIO.read(file);
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(bimage, "jpg", baos);
                byte[] img = baos.toByteArray();
                if(img.length > 128000)
                {
                    JOptionPane.showMessageDialog(this, "Ảnh bạn chọn lớn hơn kích thước tối đa (128Kb), có thể xảy ra lỗi!\nHãy chọn ảnh khác!", "Warning!!!", JOptionPane.WARNING_MESSAGE);
                }else{
                    BusForm.setImage(img);
                    BusForm.getImage(img);
                    info.setAvatar(img);
                    JOptionPane.showMessageDialog(this, "Thay ảnh thành công.");
                }
            }catch(IOException e){
                e.printStackTrace();
            }}
    }//GEN-LAST:event_Btn_thayanhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private String[] a;
            private  BufferedImage c;
            public void run() {
                try {
                    new userForm(a,c).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(userForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.MyButton Btn_thayanh;
    private javax.swing.JLabel anhthe;
    private custom.MyButton bnt_naptien;
    private custom.MyButton btn_capnhat;
    private custom.MyButton btn_changePIN;
    private custom.MyButton btn_thanhtoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_info;
    private custom.TextField txt_hoten;
    private custom.TextField txt_loaithe;
    private custom.TextField txt_ngaysinh;
    private custom.TextField txt_sodu;
    private custom.TextField txt_sothe;
    private custom.TextField txt_thoihan;
    // End of variables declaration//GEN-END:variables
}
